Repository cognizance-amrita/hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#3 chore:created folder for languages
  c++/README.md
  java/README.md
  python/README.md
Labels: enhancement

#10 Create ArrayReversal.c
  C/ArrayReversal.c
Labels: hacktoberfest-accepted

#12 chore : Updated README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#13 array.py
  python/array.py
Labels: hacktoberfest-accepted

#14 Create Stackproblem.cpp
  c++/Stackproblem.cpp
Labels: hacktoberfest-accepted

#16 Create Time Delta.py
  python/Time Delta.py
Labels: hacktoberfest-accepted

#17 Create Array_Reversal_#7.py
  python/Array_Reversal_#7.py
Labels: hacktoberfest-accepted

#18 Reverse Array in Java
  java/rev_arr.java
Labels: hacktoberfest-accepted

#21 Time in words in Java
  c++/rev_array.cpp
  java/time_in_words.java
Labels: hacktoberfest-accepted

#19 Create Stack_Problem_#2.py
  python/Stack_Problem_#2.py
Labels: hacktoberfest-accepted

#24 Finished Operator Overloading
  c++/Operator Overloading.cpp
Labels: hacktoberfest-accepted

#25 Time in words in C++
  c++/Time_in_words.cpp
Labels: hacktoberfest-accepted

#27 Create Operator_Overloading_#6.py
  python/Operator_Overloading_#6.py
Labels: hacktoberfest-accepted

#28 priority_queue.java
  java/Solution.java
Labels: hacktoberfest-accepted

#29 Create compnentsingraph.py
  python/compnentsingraph.py
Labels: hacktoberfest-accepted

#39 A_very_big_sum.c
  C/A_very_big_sum.c
Labels: hacktoberfest-accepted

#41 Staircase_#38.py
  python/Staircase_#38.py
Labels: hacktoberfest-accepted

#42 staircase problem
  java/staircase.java
Labels: hacktoberfest-accepted

#43 A_Very_Big_Sum_#30.py
  python/A_Very_Big_Sum_#30.py
Labels: hacktoberfest-accepted

#44 Left_Rotation_#40.py
  python/Left_Rotation_#40.py
Labels: hacktoberfest-accepted

#46 Created Component Connection Problem solution
  java/Graph.java
Labels: hacktoberfest-accepted

#47 Grading_Students_#34.cpp
  c++/Grading_Students_#34.cpp
Labels: hacktoberfest-accepted

#49 Staircase Problem #38
  C/Staircase.c
Labels: hacktoberfest-accepted

#50 Added Climbing Stairs problem (Dynamic Programming)
  c++/ClimbingStairs_DP.cpp
Labels: hacktoberfest-accepted

#53 LeftRotation in java
  java/leftrotation.java
Labels: hacktoberfest-accepted

#52 left rotation
  C/left_rotation.c
Labels: hacktoberfest-accepted

#51 Create Staircase.cpp
  c++/Staircase.cpp
Labels: hacktoberfest-accepted

#54 Grading_Students #34
  C/Grading_Students.c
Labels: hacktoberfest-accepted

#55 Finished Left Rotation in C++
  c++/Left Rotation.cpp
Labels: hacktoberfest-accepted

#61 Finding_the_percentage_#58.py
  python/Finding_the_percentage_#58.py
Labels: hacktoberfest-accepted

#63 Lists_#57.py
  python/Lists_#57.py
Labels: hacktoberfest-accepted

#64 Day_of_the_programmer_#59.py
  python/Day_of_the_programmer_#59.py
Labels: hacktoberfest-accepted

#71 Solved #66 in C++
  c++/Compare-The-Triplets.cpp
Labels: hacktoberfest-accepted

#72 Birthday Cake Candles #67
  java/Birthday_Cake_Candles.java
Labels: hacktoberfest-accepted

#76 Create Time Conversion.py
  python/Time Conversion.py
Labels: hacktoberfest-accepted

#74 Create Birthday_Cake_Candles #67.py
  python/Birthday_Cake_Candles #67.py
Labels: hacktoberfest-accepted

#77 Migratory_birds_#69.cpp
  c++/Migratory_birds_#69.cpp
Labels: hacktoberfest-accepted

#78 Bill_division_#70.cpp
  c++/Bill_division_#70.cpp
Labels: hacktoberfest-accepted

#79 Time_Conversion_#68.cpp
  c++/Time_Conversion_#68.cpp
Labels: hacktoberfest-accepted

#80 Birthday_cake_candles_#67.cpp
  c++/Birthday_cake_candles_#67.cpp
Labels: hacktoberfest-accepted

#82 Finding_Runner-up_score_#56.java, Bill_division_#70.java
  java/Bill_division.java
  java/Finding_the_runner_up_score.java
Labels: hacktoberfest-accepted

#83 Day_of_the_programmer_#59.java
  java/Day_of_the_programmer.java
Labels: hacktoberfest-accepted

#85 Update README.md
  README.md
Labels: documentation

#86 Update README.md
  README.md
Labels: documentation

#87 Delete_a_Node_#84.cpp
  c++/delete_node.cpp
  java/Bill_division.java
Labels: hacktoberfest-accepted

#88 time conversion program in java
  java/grading.java
  java/timeconv.java
Labels: hacktoberfest-accepted

#91 Add code of reverse doubly linked list
  C/reverse_doubly_LL.c
Labels: hacktoberfest-accepted

#95 Add files via upload
  java/grading_marks.java
Labels: hacktoberfest-accepted

#96 Add files via upload
  java/ticonv.java
Labels: hacktoberfest-accepted

#99 Add files via upload
  C/STUMARKS.C
Labels: hacktoberfest-accepted

#100 Solve Time_delta in python
  python/time_delta.py
Labels: hacktoberfest-accepted

#102 Cats_And_A_Mouse
  C/Cats_And_Mouse.c
  C/Compare_The_Triplets.c
Labels: hacktoberfest-accepted

#106 Updated pull request for Migratory Birds #69 and Cats and a Mouse #101
  c++/Finding_The_Percentage_#58.c++
  python/Cats and a Mouse #101.py
  python/Migratory Birds #69.py
Labels: hacktoberfest-accepted

#108 Issue #70 : Resolve Bill divison issue in java & python
  java/Bill_div.java
  python/Bill_div.py
Labels: hacktoberfest-accepted

#109 #58 Updated and Working
  c++/Finding_The_Percentage_#58.c++
Labels: hacktoberfest-accepted

#118 Created for #8
  python/Time_To_Word.py
Labels: hacktoberfest-accepted

#117 Issue #67 : Solve in C
  C/Birthday_Cake_candles.c
Labels: hacktoberfest-accepted

#110 Issue #101 : Resolved in java
  java/Cats_And_Mouse.java
Labels: hacktoberfest-accepted

#116 Issue #58 : Solved in java
  java/Finding_the_percentage.java
Labels: hacktoberfest-accepted

#115 Issue #69 : Solve in java
  java/Migratory_birds.java
Labels: hacktoberfest-accepted

#114 Finished Time Conversion in C
  C/Time_Conversion.c
Labels: hacktoberfest-accepted

#113 Issue #84 : Resolve in python
  java/Delete_a_node.java
  python/Delete_a_node.py
Labels: hacktoberfest-accepted

#112 cat_mouse.cpp
  c++/cat_mouse.cpp
Labels: hacktoberfest-accepted

#111 solved bill_division in java
  java/bill_divisi
Labels: hacktoberfest-accepted

#119 Create Day_of_the_programmer_#59.c
  C/Day_of_the_programmer_#59.c
  c++/Day_of_the_programmer_#59.cpp
Labels: hacktoberfest-accepted

#120 # 40 leftrotation.cpp
  c++/leftrotation.cpp
Labels: hacktoberfest-accepted

#121 # 38 issue : stair_case.c
  C/stair_case.c
Labels: hacktoberfest-accepted

#123 Finished Day of programmer in C++
  c++/Day_Of_Programmer.cpp
Labels: hacktoberfest-accepted

#126 Designer PDF viewer
  python/Designer_pdf_Viewer.py
Labels: hacktoberfest-accepted

#130 Create java_priority_queue.java
  java/java_priority_queue.java
Labels: hacktoberfest-accepted

#128 Solutions to #30 and #56
  C/Runner_up_score.c
  c++/A_very_big_sum_#30.c++
Labels: hacktoberfest-accepted

#131 issue #70 : Bill Division
  C#/Bill Division.cs
  C#/Delete a node.cs
Labels: hacktoberfest-accepted

#132 Issue #124
  c++/Designer_PDF_Viewer_#124.c++
Labels: hacktoberfest-accepted

#134 Issue #59 : Day of the programmer
  C#/Birthday Cake Candles.cs
  C#/Migratory Birds.cs
Labels: hacktoberfest-accepted

#129 Issue #124 : Contribute in Java
  java/pdfViewer.java
Labels: hacktoberfest-accepted

#135 Cat And A Mouse
  C#/A_very_big_sum.cs
  C#/Cats_and_a_Mouse.cs
Labels: hacktoberfest-accepted

#136 Added code for Castle on the Grid problem
  CastleOnTheGrid.java
Labels: hacktoberfest-accepted

#137 Solved #101 in C++
  c++/Cats-and-a-Mouse.cpp
Labels: hacktoberfest-accepted

#138 Issue : #101
  Ruby/Cats_and_a_Mouse_#101.rb
Labels: hacktoberfest-accepted

#139 Time Conversion #68
  Ruby/Time_Conversion_#68.rb
Labels: hacktoberfest-accepted

#140 Birthday Cake Candles #67
  Ruby/Birthday_Cake_Candles_#67.rb
Labels: hacktoberfest-accepted

#142 Create Compare_the_Triplets.cs
  C#/Compare_the_Triplets.cs
Labels: hacktoberfest-accepted

#143 Create Staircase.cs
  C#/Staircase.cs
Labels: hacktoberfest-accepted

#144 Added array_reversal in c#
  C#/Array_Reversal_#7.cs
Labels: hacktoberfest-accepted

#145 Added Binary_Division in C
  C/Binary_Division_#70.c
Labels: hacktoberfest-accepted

#147 Added Compare_the_triplets in Python
  c++/Find_Runnerup_Score.cpp
  python/Compare_the_triplets.py
Labels: hacktoberfest-accepted

#146 Solved #38 in cpp
  c++/stair.cpp
Labels: hacktoberfest-accepted

#148 Added Coin_Change_Problem in Java
  java/Coin_Change_Problem.java
Labels: hacktoberfest-accepted
